version: "3.7"

networks:
  n_traefik_proxy:
    external: true

volumes:
  v_portainer:
    external: true

services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    restart: always
    hostname: traefik
    networks:
      - default
      - n_traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      traefik.enable: "true"
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.${DOMAINNAME}"
      traefik.port: "8080"
      traefik.docker.network: "traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERDIR}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${DOCKERDIR}/traefik/acme.json:/etc/traefik/acme/acme.json
    command: --acme.domains="${DOMAINNAME}" \
             --acme.email="${ACME_EMAIL}" \
             --docker.domain="${DOMAINNAME}"

  portainer:
    image: portainer/portainer:linux-arm
    container_name: portainer
    restart: always
    networks:
      - n_traefik_proxy
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.frontend.rule: "Host:portainer.${DOMAINNAME}"
      traefik.docker.network: "traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - v_portainer:/data

  watchtower:
    image: containrrr/watchtower:armhf-latest
    container_name: watchtower
    restart: always
    labels:
      traefik.enable: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup

  whoami:
    image: hypriot/rpi-whoami
    container_name: whoami
    restart: always
    networks:
      - n_traefik_proxy
    labels:
      traefik.enable: "true"
      traefik.backend: "whoami"
      traefik.frontend.rule: "Host:whoami.${DOMAINNAME}"
      traefik.docker.network: "traefik_proxy"
