version: '3.7'

networks:
  n_traefik_proxy:
    external: true

volumes:
  v_portainer:
    external: true

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    hostname: traefik
    networks:
      - default
      - n_traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      traefik.enable: "true"
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.${DOMAINNAME}"
      traefik.port: "8080"
      traefik.docker.network: "n_traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/${USER}/mydockerpi/infrastructure/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /home/${USER}/mydockerpi/infrastructure/traefik/acme.json:/etc/traefik/acme/acme.json
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    command: --acme.domains="${DOMAINNAME}" \
             --acme.email="${ACME_EMAIL}" \
             --docker.domain="${DOMAINNAME}"

  portainer:
    image: portainer/portainer:latest
    restart: always
    networks:
      - n_traefik_proxy
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.frontend.rule: "Host:portainer.${DOMAINNAME}"
      traefik.docker.network: "n_traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - v_portainer:/data
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
