version: '3.7'

volumes:
  v_kodidb:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    network_mode: "host"
    labels:
      traefik.enable: "false"
    volumes:
      - /home/${USER}/mydockerpi/jellyfin/data/config:/config
      - /home/${USER}/mydockerpi/jellyfin/data/cache:/cache
      - /home/${USER}/mydockerpi/jellyfin/data/media:/media
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
