# print only error messages
debug = false

logLevel = "ERROR"

# allow ingress trafic on port 80 and 443
# redirect trafic from port 80 to 443
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# retry request when network errors apear; default 3 times
[retry]

# enable traefik dashboard on port 8080
[api]

# enable traefik to discover new container by their traefik-labels on your docker host
[docker]
endpoint = "unix:///var/run/docker.sock"
# Domain will be set by variables in compose file.
# domain = ""
watch = true
exposedByDefault = false

# enable the acme to issue Let's Encrypt SSL-Certificates
[acme]
# Email will be set by variables in compose file.
# email = ""
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
onHostRule = true
acmeLogging = true
[acme.httpChallenge]
entryPoint = "http"

# Acme domains will be set by variables in compose file.
# [[acme.domains]]
#  main = ""
